.TH "com.project.base.OnErrorListener" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.base.OnErrorListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonError\fP (Throwable error)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn
.RE
.PP
Ten interface obsługuje zgłaszanie błędu podczas wykonania \fBUseCase\fP'a\&. 
.SH "Member Function Documentation"
.PP 
.SS "void com\&.project\&.base\&.OnErrorListener\&.onError (Throwable error)"

.PP
\fBParameters:\fP
.RS 4
\fIerror\fP - błąd zgłoszony podczas wykonania operacji 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
