.TH "com.project.entity.ProductEntity" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.entity.ProductEntity
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProductEntity\fP ()"
.br
.ti -1c
.RI "\fBProductEntity\fP (String remoteId, String category, String name, String params, String price, Double score, String reviewsDesc)"
.br
.ti -1c
.RI "Long \fBgetId\fP ()"
.br
.ti -1c
.RI "String \fBgetRemoteId\fP ()"
.br
.ti -1c
.RI "void \fBsetReviews\fP (Collection< \fBReviewEntity\fP > reviews)"
.br
.ti -1c
.RI "Collection< \fBReviewEntity\fP > \fBgetReviews\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (Long id)"
.br
.ti -1c
.RI "String \fBgetCategory\fP ()"
.br
.ti -1c
.RI "void \fBsetCategory\fP (String category)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetParams\fP ()"
.br
.ti -1c
.RI "void \fBsetParams\fP (String params)"
.br
.ti -1c
.RI "String \fBgetPrice\fP ()"
.br
.ti -1c
.RI "void \fBsetPrice\fP (String price)"
.br
.ti -1c
.RI "Double \fBgetScore\fP ()"
.br
.ti -1c
.RI "void \fBsetScore\fP (Double score)"
.br
.ti -1c
.RI "String \fBgetReviewsDesc\fP ()"
.br
.ti -1c
.RI "void \fBsetReviewsDesc\fP (String reviewsDesc)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn
.RE
.PP
Encja definiująca tabelę produktów w bazie danych\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.project\&.entity\&.ProductEntity\&.ProductEntity ()"
Konstruktor domyślny 
.SS "com\&.project\&.entity\&.ProductEntity\&.ProductEntity (String remoteId, String category, String name, String params, String price, Double score, String reviewsDesc)"

.PP
\fBParameters:\fP
.RS 4
\fIremoteId\fP 
.br
\fIcategory\fP 
.br
\fIname\fP 
.br
\fIparams\fP 
.br
\fIprice\fP 
.br
\fIscore\fP 
.br
\fIreviewsDesc\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String com\&.project\&.entity\&.ProductEntity\&.getCategory ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "Long com\&.project\&.entity\&.ProductEntity\&.getId ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "String com\&.project\&.entity\&.ProductEntity\&.getName ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "String com\&.project\&.entity\&.ProductEntity\&.getParams ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "String com\&.project\&.entity\&.ProductEntity\&.getPrice ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "String com\&.project\&.entity\&.ProductEntity\&.getRemoteId ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "Collection<\fBReviewEntity\fP> com\&.project\&.entity\&.ProductEntity\&.getReviews ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "String com\&.project\&.entity\&.ProductEntity\&.getReviewsDesc ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "Double com\&.project\&.entity\&.ProductEntity\&.getScore ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setCategory (String category)"

.PP
\fBParameters:\fP
.RS 4
\fIcategory\fP 
.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setId (Long id)"

.PP
\fBParameters:\fP
.RS 4
\fIid\fP 
.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setName (String name)"

.PP
\fBParameters:\fP
.RS 4
\fIname\fP 
.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setParams (String params)"

.PP
\fBParameters:\fP
.RS 4
\fIparams\fP 
.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setPrice (String price)"

.PP
\fBParameters:\fP
.RS 4
\fIprice\fP 
.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setReviews (Collection< \fBReviewEntity\fP > reviews)"

.PP
\fBParameters:\fP
.RS 4
\fIreviews\fP 
.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setReviewsDesc (String reviewsDesc)"

.PP
\fBParameters:\fP
.RS 4
\fIreviewsDesc\fP 
.RE
.PP

.SS "void com\&.project\&.entity\&.ProductEntity\&.setScore (Double score)"

.PP
\fBParameters:\fP
.RS 4
\fIscore\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
