.TH "com.project.provider.IProductProvider" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.provider.IProductProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherited by com\&.project\&.application\&.ProductProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBProductDTO\fP > \fBgetProducts\fP (String searchQuery)  throws ProviderException"
.br
.ti -1c
.RI "\fBProductDTO\fP \fBgetProduct\fP (String searchQuery)  throws ProviderException"
.br
.ti -1c
.RI "List< \fBReviewDTO\fP > \fBgetReviews\fP (String productId)  throws ProviderException"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
