.TH "com.project.dto.ProductReviewsDTO" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.dto.ProductReviewsDTO
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProductReviewsDTO\fP (\fBProductDTO\fP product, Collection< \fBReviewDTO\fP > reviews)"
.br
.ti -1c
.RI "\fBProductDTO\fP \fBgetProduct\fP ()"
.br
.ti -1c
.RI "Collection< \fBReviewDTO\fP > \fBgetReviews\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn
.RE
.PP
Struktura DTO przechowująca obiekt z danymi produktu oraz jego listą opini\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.project\&.dto\&.ProductReviewsDTO\&.ProductReviewsDTO (\fBProductDTO\fP product, Collection< \fBReviewDTO\fP > reviews)"

.PP
\fBParameters:\fP
.RS 4
\fIproduct\fP dane produktu 
.br
\fIreviews\fP lista opini 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBProductDTO\fP com\&.project\&.dto\&.ProductReviewsDTO\&.getProduct ()"

.PP
\fBReturns:\fP
.RS 4
dane produktu 
.RE
.PP

.SS "Collection<\fBReviewDTO\fP> com\&.project\&.dto\&.ProductReviewsDTO\&.getReviews ()"

.PP
\fBReturns:\fP
.RS 4
lista opini 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
