.TH "com.project.dto.ProductDTO" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.dto.ProductDTO
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProductDTO\fP ()"
.br
.ti -1c
.RI "\fBProductDTO\fP (String remoteId)"
.br
.ti -1c
.RI "String \fBgetRemoteId\fP ()"
.br
.ti -1c
.RI "void \fBsetRemoteId\fP (String remoteId)"
.br
.ti -1c
.RI "String \fBgetCategory\fP ()"
.br
.ti -1c
.RI "void \fBsetCategory\fP (String category)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetParams\fP ()"
.br
.ti -1c
.RI "void \fBsetParams\fP (String params)"
.br
.ti -1c
.RI "String \fBgetPrice\fP ()"
.br
.ti -1c
.RI "void \fBsetPrice\fP (String price)"
.br
.ti -1c
.RI "Double \fBgetScore\fP ()"
.br
.ti -1c
.RI "void \fBsetScore\fP (Double score)"
.br
.ti -1c
.RI "String \fBgetReviewsDesc\fP ()"
.br
.ti -1c
.RI "void \fBsetReviewsDesc\fP (String reviewsDesc)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn
.RE
.PP
Struktura DTO przechowująca dane produktu\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.project\&.dto\&.ProductDTO\&.ProductDTO ()"
Konstruktor domyślny 
.SS "com\&.project\&.dto\&.ProductDTO\&.ProductDTO (String remoteId)"

.PP
\fBParameters:\fP
.RS 4
\fIremoteId\fP zdalne id produktu 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String com\&.project\&.dto\&.ProductDTO\&.getCategory ()"

.PP
\fBReturns:\fP
.RS 4
kategoria 
.RE
.PP

.SS "String com\&.project\&.dto\&.ProductDTO\&.getName ()"

.PP
\fBReturns:\fP
.RS 4
nazwa 
.RE
.PP

.SS "String com\&.project\&.dto\&.ProductDTO\&.getParams ()"

.PP
\fBReturns:\fP
.RS 4
parametry 
.RE
.PP

.SS "String com\&.project\&.dto\&.ProductDTO\&.getPrice ()"

.PP
\fBReturns:\fP
.RS 4
cena 
.RE
.PP

.SS "String com\&.project\&.dto\&.ProductDTO\&.getRemoteId ()"

.PP
\fBReturns:\fP
.RS 4
zdalne id produktu 
.RE
.PP

.SS "String com\&.project\&.dto\&.ProductDTO\&.getReviewsDesc ()"

.PP
\fBReturns:\fP
.RS 4
opis opini 
.RE
.PP

.SS "Double com\&.project\&.dto\&.ProductDTO\&.getScore ()"

.PP
\fBReturns:\fP
.RS 4
średnia ocena 
.RE
.PP

.SS "void com\&.project\&.dto\&.ProductDTO\&.setCategory (String category)"

.PP
\fBParameters:\fP
.RS 4
\fIcategory\fP kategoria 
.RE
.PP

.SS "void com\&.project\&.dto\&.ProductDTO\&.setName (String name)"

.PP
\fBParameters:\fP
.RS 4
\fIname\fP nazwa 
.RE
.PP

.SS "void com\&.project\&.dto\&.ProductDTO\&.setParams (String params)"

.PP
\fBParameters:\fP
.RS 4
\fIparams\fP parametry 
.RE
.PP

.SS "void com\&.project\&.dto\&.ProductDTO\&.setPrice (String price)"

.PP
\fBParameters:\fP
.RS 4
\fIprice\fP cena 
.RE
.PP

.SS "void com\&.project\&.dto\&.ProductDTO\&.setRemoteId (String remoteId)"

.PP
\fBParameters:\fP
.RS 4
\fIremoteId\fP zdalne id produktu 
.RE
.PP

.SS "void com\&.project\&.dto\&.ProductDTO\&.setReviewsDesc (String reviewsDesc)"

.PP
\fBParameters:\fP
.RS 4
\fIreviewsDesc\fP opis opini 
.RE
.PP

.SS "void com\&.project\&.dto\&.ProductDTO\&.setScore (Double score)"

.PP
\fBParameters:\fP
.RS 4
\fIscore\fP średnia ocena 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
