.TH "com.project.base.OnSuccessListener< RESULT_OBJECT >" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.base.OnSuccessListener< RESULT_OBJECT >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonSuccess\fP (RESULT_OBJECT result)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn
.RE
.PP
Ten interface obsługuje wynik operacji wykonania \fBUseCase\fP'a\&.
.PP
\fBParameters:\fP
.RS 4
\fI<RESULT_OBJECT>\fP - typ wyniku operacji 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void \fBcom\&.project\&.base\&.OnSuccessListener\fP< RESULT_OBJECT >\&.onSuccess (RESULT_OBJECT result)"

.PP
\fBParameters:\fP
.RS 4
\fIresult\fP wynik operacji 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
