.TH "com.project.data.IProductRepository" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.data.IProductRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherited by com\&.project\&.application\&.ProductRepository\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBProductEntity\fP > \fBloadProducts\fP ()  throws DatabaseException"
.br
.ti -1c
.RI "void \fBsaveProduct\fP (\fBProductEntity\fP productEntity)  throws DatabaseException"
.br
.ti -1c
.RI "List< \fBReviewEntity\fP > \fBloadReviews\fP ()  throws DatabaseException"
.br
.ti -1c
.RI "List< \fBReviewEntity\fP > \fBloadReviews\fP (String productId)  throws DatabaseException"
.br
.ti -1c
.RI "void \fBsaveReview\fP (String productRemoteId, \fBReviewEntity\fP reviewEntity)  throws DatabaseException"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
