.TH "com.project.base.DatabaseException" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.base.DatabaseException
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabaseException\fP (Throwable cause)"
.br
.ti -1c
.RI "\fBDatabaseException\fP (String message)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
