.TH "com.project.data.IORMLiteDataBaseService" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.data.IORMLiteDataBaseService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by com\&.project\&.application\&.ORMLiteDataBaseService\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetDatabaseName\fP ()"
.br
.ti -1c
.RI "boolean \fBdataBaseExists\fP ()"
.br
.ti -1c
.RI "\fBIORMLiteDataBase\fP \fBcreateDataBase\fP ()"
.br
.ti -1c
.RI "\fBIORMLiteDataBase\fP \fBprovideDataBase\fP ()"
.br
.ti -1c
.RI "void \fBclearDatabase\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
