.TH "com.project.application.ExportReviewsArgument" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.application.ExportReviewsArgument
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExportReviewsArgument\fP (\fBExportReviewsFormat\fP format, String fileName, String productRemoteId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "final \fBExportReviewsFormat\fP \fBformat\fP"
.br
.ti -1c
.RI "final String \fBproductRemoteId\fP"
.br
.ti -1c
.RI "final String \fBfileName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn
.RE
.PP
Argument zawierający konfiguracje eksportu opini\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.project\&.application\&.ExportReviewsArgument\&.ExportReviewsArgument (\fBExportReviewsFormat\fP format, String fileName, String productRemoteId)"

.PP
\fBParameters:\fP
.RS 4
\fIformat\fP - format eksportowanych opini 
.br
\fIfileName\fP - nazwa pliku 
.br
\fIproductRemoteId\fP - id product to wyeksportowania opini 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
