.TH "com.project.provider.IWebClientService" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.provider.IWebClientService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by com\&.project\&.application\&.WebClientService\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBget\fP (String url)  throws ProviderException"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
