.TH "com.project.dto.ReviewDTO" 3 "Tue Jan 9 2018" "CeneoHD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.project.dto.ReviewDTO
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReviewDTO\fP (String remoteId)"
.br
.ti -1c
.RI "String \fBgetRemoteId\fP ()"
.br
.ti -1c
.RI "String \fBgetAdvantages\fP ()"
.br
.ti -1c
.RI "void \fBsetAdvantages\fP (String advantages)"
.br
.ti -1c
.RI "String \fBgetDisadvantages\fP ()"
.br
.ti -1c
.RI "void \fBsetDisadvantages\fP (String disadvantages)"
.br
.ti -1c
.RI "String \fBgetSummary\fP ()"
.br
.ti -1c
.RI "void \fBsetSummary\fP (String summary)"
.br
.ti -1c
.RI "String \fBgetScore\fP ()"
.br
.ti -1c
.RI "void \fBsetScore\fP (String score)"
.br
.ti -1c
.RI "String \fBgetAuthor\fP ()"
.br
.ti -1c
.RI "void \fBsetAuthor\fP (String author)"
.br
.ti -1c
.RI "Date \fBgetCreateDate\fP ()"
.br
.ti -1c
.RI "void \fBsetCreateDate\fP (Date createDate)"
.br
.ti -1c
.RI "Boolean \fBgetIsRecomended\fP ()"
.br
.ti -1c
.RI "void \fBsetIsRecomended\fP (Boolean isRecomended)"
.br
.ti -1c
.RI "int \fBgetLikesCount\fP ()"
.br
.ti -1c
.RI "void \fBsetLikesCount\fP (int likesCount)"
.br
.ti -1c
.RI "int \fBgetDislikesCount\fP ()"
.br
.ti -1c
.RI "void \fBsetDislikesCount\fP (int dislikesCount)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
seweryn
.RE
.PP
Struktura DTO przechowująca dane opini\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.project\&.dto\&.ReviewDTO\&.ReviewDTO (String remoteId)"

.PP
\fBParameters:\fP
.RS 4
\fIremoteId\fP zdalne id opini 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String com\&.project\&.dto\&.ReviewDTO\&.getAdvantages ()"

.PP
\fBReturns:\fP
.RS 4
the advantages 
.RE
.PP

.SS "String com\&.project\&.dto\&.ReviewDTO\&.getAuthor ()"

.PP
\fBReturns:\fP
.RS 4
the author 
.RE
.PP

.SS "Date com\&.project\&.dto\&.ReviewDTO\&.getCreateDate ()"

.PP
\fBReturns:\fP
.RS 4
the createDate 
.RE
.PP

.SS "String com\&.project\&.dto\&.ReviewDTO\&.getDisadvantages ()"

.PP
\fBReturns:\fP
.RS 4
the disadvantages 
.RE
.PP

.SS "int com\&.project\&.dto\&.ReviewDTO\&.getDislikesCount ()"

.PP
\fBReturns:\fP
.RS 4
the dislikesCount 
.RE
.PP

.SS "Boolean com\&.project\&.dto\&.ReviewDTO\&.getIsRecomended ()"

.PP
\fBReturns:\fP
.RS 4
the isRecomended 
.RE
.PP

.SS "int com\&.project\&.dto\&.ReviewDTO\&.getLikesCount ()"

.PP
\fBReturns:\fP
.RS 4
the likesCount 
.RE
.PP

.SS "String com\&.project\&.dto\&.ReviewDTO\&.getRemoteId ()"

.PP
\fBReturns:\fP
.RS 4
zdalne id opini 
.RE
.PP

.SS "String com\&.project\&.dto\&.ReviewDTO\&.getScore ()"

.PP
\fBReturns:\fP
.RS 4
the score 
.RE
.PP

.SS "String com\&.project\&.dto\&.ReviewDTO\&.getSummary ()"

.PP
\fBReturns:\fP
.RS 4
the summary 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setAdvantages (String advantages)"

.PP
\fBParameters:\fP
.RS 4
\fIadvantages\fP the advantages to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setAuthor (String author)"

.PP
\fBParameters:\fP
.RS 4
\fIauthor\fP the author to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setCreateDate (Date createDate)"

.PP
\fBParameters:\fP
.RS 4
\fIcreateDate\fP the createDate to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setDisadvantages (String disadvantages)"

.PP
\fBParameters:\fP
.RS 4
\fIdisadvantages\fP the disadvantages to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setDislikesCount (int dislikesCount)"

.PP
\fBParameters:\fP
.RS 4
\fIdislikesCount\fP the dislikesCount to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setIsRecomended (Boolean isRecomended)"

.PP
\fBParameters:\fP
.RS 4
\fIisRecomended\fP the isRecomended to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setLikesCount (int likesCount)"

.PP
\fBParameters:\fP
.RS 4
\fIlikesCount\fP the likesCount to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setScore (String score)"

.PP
\fBParameters:\fP
.RS 4
\fIscore\fP the score to set 
.RE
.PP

.SS "void com\&.project\&.dto\&.ReviewDTO\&.setSummary (String summary)"

.PP
\fBParameters:\fP
.RS 4
\fIsummary\fP the summary to set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CeneoHD from the source code\&.
