/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.importer;

import com.project.CeneoHDApplication;
import com.project.application.SaveProductUseCase;
import com.project.base.UseCaseExecutor;
import com.project.dto.ProductDTO;
import com.project.entity.ProductEntity;

/**
 *
 * @author seweryn
 */
public class LoadImporterPanel extends javax.swing.JPanel {

    public interface Listener{
        
        void displayException(Throwable ex);
        
        void onLoadSuccess( );
        
    }
    
    private Listener parentListener;
    
    private ProductEntity productEntity;
    
    private final UseCaseExecutor executor;
    
    private final SaveProductUseCase saveProductUseCase;
    /**
     * Creates new form LoadImporterPanel
     */
    public LoadImporterPanel() {
        initComponents();
        executor = CeneoHDApplication.get().provideCeneoHDComponent().provideUseCaseExecutor();
        saveProductUseCase = CeneoHDApplication.get().provideCeneoHDComponent().provideSaveProductUseCase();
    }
    
    public void displayProduct( ProductEntity productEntity ){
        this.productEntity = productEntity;
    }
    
    public void setParentListener( Listener parentListener ){
        this.parentListener = parentListener; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFinish = new javax.swing.JButton();

        jButtonFinish.setText("finish");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jButtonFinish)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jButtonFinish)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        
        executor.execute(saveProductUseCase, productEntity, data -> {
            parentListener.onLoadSuccess();
        }, ex -> {
            parentListener.displayException(ex);
        });
        
    }//GEN-LAST:event_jButtonFinishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinish;
    // End of variables declaration//GEN-END:variables
}
