/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.importer;

import com.project.CeneoHDApplication;
import com.project.application.SaveProductUseCase;
import com.project.base.UseCaseExecutor;
import com.project.dto.ProductDTO;
import com.project.entity.ProductEntity;

/**
 *
 * @author seweryn
 */
public class LoadImporterPanel extends javax.swing.JPanel {

    public interface Listener{
        
        void displayException(Throwable ex);
        
        void onLoadSuccess( );
        
    }
    
    private Listener parentListener;
    
    private ProductEntity productEntity;
    
    private final UseCaseExecutor executor;
    
    private final SaveProductUseCase saveProductUseCase;
    /**
     * Creates new form LoadImporterPanel
     */
    public LoadImporterPanel() {
        initComponents();
        executor = CeneoHDApplication.get().provideCeneoHDComponent().provideUseCaseExecutor();
        saveProductUseCase = CeneoHDApplication.get().provideCeneoHDComponent().provideSaveProductUseCase();
    }
    
    public void displayProduct( ProductEntity productEntity ){
        this.productEntity = productEntity;
        jLabel1.setText("Reviews to save: " + productEntity.getReviews().size());
    }
    
    public void setParentListener( Listener parentListener ){
        this.parentListener = parentListener; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFinish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButtonFinish.setText("finish");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        jLabel1.setText("Reviews to add: 133");

        jLabel2.setText("Load product to data warehouse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 308, Short.MAX_VALUE)
                        .addComponent(jButtonFinish))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jButtonFinish)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        
        executor.execute(saveProductUseCase, productEntity, data -> {
            parentListener.onLoadSuccess();
        }, ex -> {
            parentListener.displayException(ex);
        });
        
    }//GEN-LAST:event_jButtonFinishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
