/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.importer;

import com.project.CeneoHDApplication;
import com.project.application.TransformProductUseCase;
import com.project.base.UseCaseExecutor;
import com.project.dto.ProductDTO;
import com.project.dto.ProductReviewsDTO;
import com.project.entity.ProductEntity;

/**
 *
 * @author seweryn
 */
public class TransformImporterPanel extends javax.swing.JPanel {

    public interface Listener{
        
        void displayException(Throwable ex);
        
        void onTransformSuccess( ProductEntity productEntity );
        
    }
    
    private final UseCaseExecutor executor;
    
    private final TransformProductUseCase transformProductUseCase;
    
    private Listener parentListener;
    
    private ProductReviewsDTO productDto;
    /**
     * Creates new form TransformImporterPanel
     */
    public TransformImporterPanel() {
        initComponents();
        executor = CeneoHDApplication.get().provideCeneoHDComponent().provideUseCaseExecutor();
        transformProductUseCase = CeneoHDApplication.get().provideCeneoHDComponent().provideTransformProductUseCase();
    }
    
    public void setParentListener( Listener parentListener ){
        this.parentListener = parentListener; 
    }

    public void displayProduct( ProductReviewsDTO dto ){
        this.productDto = dto;
        jLabel1.setText( "Found reviews: " + dto.getReviews().size() );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButtonNext.setText("next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabel1.setText("Found reviews: 232");
        jLabel1.setToolTipText("");

        jLabel2.setText("Transform product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 313, Short.MAX_VALUE)
                        .addComponent(jButtonNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(jButtonNext)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        executor.execute(transformProductUseCase, productDto, product -> {
            parentListener.onTransformSuccess(product);
        }, ex -> {
            parentListener.displayException(ex);
        });
        
    }//GEN-LAST:event_jButtonNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
