/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.importer;

import com.project.CeneoHDApplication;
import com.project.application.TransformProductUseCase;
import com.project.base.UseCaseExecutor;
import com.project.dto.ProductDTO;
import com.project.entity.ProductEntity;

/**
 *
 * @author seweryn
 */
public class TransformImporterPanel extends javax.swing.JPanel {

    public interface Listener{
        
        void displayException(Throwable ex);
        
        void onTransformSuccess( ProductEntity productEntity );
        
    }
    
    private final UseCaseExecutor executor;
    
    private final TransformProductUseCase transformProductUseCase;
    
    private Listener parentListener;
    
    private ProductDTO productDto;
    /**
     * Creates new form TransformImporterPanel
     */
    public TransformImporterPanel() {
        initComponents();
        executor = CeneoHDApplication.get().provideCeneoHDComponent().provideUseCaseExecutor();
        transformProductUseCase = CeneoHDApplication.get().provideCeneoHDComponent().provideTransformProductUseCase();
    }
    
    public void setParentListener( Listener parentListener ){
        this.parentListener = parentListener; 
    }

    public void displayProduct( ProductDTO dto ){
        this.productDto = dto;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNext = new javax.swing.JButton();

        jButtonNext.setText("next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(jButtonNext)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jButtonNext)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        executor.execute(transformProductUseCase, productDto, product -> {
            parentListener.onTransformSuccess(product);
        }, ex -> {
            parentListener.displayException(ex);
        });
        
    }//GEN-LAST:event_jButtonNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    // End of variables declaration//GEN-END:variables
}
